<footer>
    <ul class="footer flex-container">
        <li class="flex-normal"><a href="home.html" class="sy_bg1 font-normal">首页</a></li>
        <li class="flex-normal"><a href="search.html" class="fx_bg font-normal">发现</a></li>
        <li class="flex-normal"><a href="messages.html" class="xx_bg font-normal">消息</a></li>
        <li class="flex-normal"><a href="user.html" class="wd_bg font-normal">我的</a></li>
    </ul>
</footer> 