<footer>
    <ul class="footer flex-container">
        <li class="flex-normal">
            <a href="home.html" class="active font-normal">
                <div class="font-super iconfont icon-homeH"></div>
                首页
            </a>
        </li>
        <li class="flex-normal">
            <a href="search.html" class="font-normal">
                <div class="font-super iconfont icon-findH"></div>
                发现
            </a>
        </li>
        <li class="flex-normal">
            <a href="messages.html" class="font-normal">
                <div class="font-super iconfont icon-message"></div>
                消息
            </a>
        </li>
        <li class="flex-normal">
            <a href="user.html" class="font-normal">
                <div class="font-super iconfont icon-user"></div>
                我的
            </a>
        </li>
    </ul>
</footer> 